# Generated by Django 4.0.5 on 2022-07-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadline_Day',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline_Time',
        ),
    ]
