# Generated by Django 4.0.5 on 2022-06-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_taskhandler_client_is_taskhandler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
