# Generated by Django 4.0.5 on 2022-07-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_deadline_day_task_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadline',
            new_name='deadline_date',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
