# Generated by Django 4.0.5 on 2022-07-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_deadline_task_deadline_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline_time',
        ),
    ]
