# Generated by Django 4.0.5 on 2022-06-27 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_client_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskhandler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.client'),
        ),
    ]
