# Generated by Django 4.0.5 on 2022-06-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_customuser_is_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='client',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='taskhandler',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='taskhandler',
            name='LastName',
        ),
        migrations.AddField(
            model_name='customuser',
            name='FirstName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='LastName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
