# Generated by Django 4.0.5 on 2022-07-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_deadline_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline_date',
        ),
    ]
