# Generated by Django 4.0.5 on 2022-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
