# Generated by Django 4.0.5 on 2022-06-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_client_firstname_remove_client_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='FirstName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='LastName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taskhandler',
            name='FirstName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taskhandler',
            name='LastName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
