# Generated by Django 4.0.5 on 2022-07-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_deadline_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadline_date',
            new_name='deadline',
        ),
    ]
