# Generated by Django 4.0.5 on 2022-06-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_client_firstname_client_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='LastName',
        ),
    ]
