# Generated by Django 4.0.5 on 2022-06-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='FirstName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='LastName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
