# Generated by Django 4.0.5 on 2022-07-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_status_submit_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.DeleteModel(
            name='submit_Task',
        ),
    ]
