# Generated by Django 4.0.5 on 2022-07-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_file2_delete_submit_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='file2',
            new_name='submit_files',
        ),
    ]
