# Generated by Django 4.0.5 on 2022-07-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_file2_task_submit_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submit_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
