# Generated by Django 4.0.5 on 2022-07-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_submit_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='submit_description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='submit_files',
        ),
    ]
