# Generated by Django 4.0.5 on 2022-07-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_task_submit_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Claimed', 'Claimed'), ('Submitted', 'Submitted'), ('Paid', 'Paid')], default='Available', max_length=200, null=True),
        ),
    ]
