# Generated by Django 4.0.5 on 2022-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Submit_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Submit_Files',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
