# Generated by Django 4.0.5 on 2022-07-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_submit_description_task_submit_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Submit_Image',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
