# Generated by Django 4.0.6 on 2022-07-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_submit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Claimed', 'Claimed'), ('Under Review', 'Under Review'), ('Submitted', 'Submitted'), ('Paid', 'Paid')], default='Available', max_length=200, null=True),
        ),
    ]
