# Generated by Django 4.0.6 on 2022-08-26 16:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Submit_Description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Submit_Description_report',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
