# Generated by Django 4.0.6 on 2022-08-26 18:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_task_submit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_complaint',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Claimed', 'Claimed'), ('Under Review', 'Under Review'), ('Flagged', 'Flagged'), ('Submitted', 'Submitted'), ('Paid', 'Paid')], default='Available', max_length=200, null=True),
        ),
    ]
