# Generated by Django 4.0.6 on 2022-09-08 14:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_task_client_complaint_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Submit_Description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Submit_Files',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Submit_Image',
            field=models.ImageField(default='profile_pic.jpg', null=True, upload_to='files'),
        ),
    ]
